import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";
import { ToastProvider } from "@/components/providers/toaster-provider";
import { CookiesProvider } from "next-client-cookies/server";
import { UserContext, UserProvider } from "@/useContext/UserProvider";

const mulish = Mulish({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bislerium",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mulish.className} suppressHydrationWarning={true}>
        <ToastProvider />
        <CookiesProvider>
          <UserProvider>{children}</UserProvider>
        </CookiesProvider>
      </body>
    </html>
  );
}
